name: action release download
description: Download action release
author: romnn <contact@romnn.com>
branding:
  icon: box
  color: orange
inputs:
  assets:
    description: "An single asset name, glob pattern, or template, or stringified YAML sequence"
    required: true
  repo:
    description: "GitHub repository to download from"
    # default: "${{github.action_repository}}"
    # default: "${{ github.event.repository.name }}"
    default: "${{ github.repository }}"
  version:
    description: "Release version to install"
    default: "latest"
  token:
    description: "Github API token"
    default: "${{ github.token }}"
    required: false
  github-api-url:
    description: "The URL of the Github API, only use this input if you are using Github Enterprise"
    default: "https://api.github.com"
    required: false
outputs:
  tag_name:
    description: "The github tag used to download the release"
  release_name:
    description: "The release name / title"
  downloaded_files:
    description: "The array of downloaded files, useful when using wildcard '*' to download multiple files."
runs:
  using: node20
  main: action/dist/index.js
