# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
includes:
  lib:
    taskfile: "./tasks/node-lib.yaml"
    vars:
      PACKAGE: "action-get-release"

  action:
    taskfile: "./tasks/node.yaml"
    vars:
      PACKAGE: "action-get-release-action"
tasks:
  install:
    desc: "install dependencies"
    cmds:
      - npm install --include=dev

  check:
    desc: "check workspace"
    cmds:
      - npm run check

  build:
    desc: "build workspace"
    cmds:
      - npm run build

  lint:
    desc: "lint workspace"
    cmds:
      - npm run lint

  lint:fix:
    desc: "lint and fix workspace"
    cmds:
      - npm run lint:fix

  test:
    desc: "test workspace"
    cmds:
      - npm run test

  format:
    desc: "format"
    cmds:
      - npm run format

  typos:
    desc: "check repository for typos"
    aliases: [spellcheck]
    cmds:
      - typos

  lint:actions:
    desc: "lint github actions"
    cmds:
      - actionlint

  packlist:
    desc: "check what is included in the NPM package"
    cmds:
      - npx npm-packlist
