# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: release

on:
  push:
    tags:
      - "*"

env:
  MISE_GITHUB_TOKEN: ${{ github.token }}
  MISE_AUTO_INSTALL: "0"

jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  publish:
    runs-on: ubuntu-24.04
    needs: [tests]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install: false
          cache: true
          env: false
      - run: mise install task node pnpm
      - id: query
        uses: romnn/query-git-action@main
      - name: set library version
        working-directory: ./action-get-release
        run: >-
          pnpm version
          --no-git-tag-version ${{ steps.query.outputs.semver_version }}
      - run: task install
      - run: task build
      - run: pnpm --filter action-get-release publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
