name: release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: query
        uses: romnn/query-git-action@main
      - uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - run: >
          npm version 
          --no-git-tag-version ${{ steps.query.outputs.semver_version }}
      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
