name: test

on:
  push: {}
  pull_request: {}
  schedule:
    # 8AM first day of the month in JAN and JUNE to keep workflow badges up-to-date
    - cron: "0 8 1 1,6 *"

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn run test
      - name: Test example
        run: |
          cd examples/
          yarn install --dev
          yarn run run || true
          file ./tmp/publish-crates-action
