name: test

on:
  push: {}
  pull_request: {}
  schedule:
    # 8AM first day of the month in JAN and JUNE to keep workflow badges up-to-date
    - cron: "0 8 1 1,6 *"

jobs:
  test-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: task install
      - run: npm install -g turbo
      - run: task action:build

      - name: Pass single asset
        continue-on-error: true
        uses: ./
        with:
          assets: test1.zip

      - name: Pass multiple assets as YAML string
        continue-on-error: true
        uses: ./
        with:
          assets: |
            - test1.zip
            - test2.zip

  test:
    runs-on: ubuntu-24.04
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: task install
      - run: npm install -g turbo
      - run: task test
      # - name: Test example
      #   run: |
      #     cd examples/
      #     yarn install --dev
      #     yarn run run || true
      #     file ./tmp/publish-crates-action
