name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (node ${{ matrix.node-version }})
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x
          - 19.x
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn run test

      - name: Test example
        env:
          GITHUB_REPOSITORY: romnn/ldap-manager
          GITHUB_ACTION_REPOSITORY: romnn/publish-crates
          RUNNER_TEMP: ./tmp
        run: |
          cd examples/
          mkdir ./tmp
          yarn install --dev
          yarn run run
