name: test

on:
  push: {}
  pull_request: {}
  schedule:
    # 8AM first day of the month in JAN and JUNE to keep workflow badges up-to-date
    - cron: "0 8 1 1,6 *"

jobs:
  test-action:
    name: test action (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, ubuntu-24.04, windows-2025]
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: task install
      - run: npm install -g turbo
      - run: task action:build

      - name: Test cargo feature combinations
        uses: ./
        with:
          version: "v0.0.39"
          repo: romnn/cargo-feature-combinations
          expected-matching-asset-count: 2
          # prettier-ignore
          assets: |
            - >-
              *cargo-*
              {{~#switch platform ~}}
                {{~#case "win32"~}}windows{{~/case~}}
                {{~#default~}}{{~platform~}}{{~/default~}}
              {{~/switch~}}
              _
              {{~#switch arch ~}}
              {{~#case "x64"~}}amd64{{~/case~}}
              {{~#default~}}{{~arch~}}{{~/default~}}
              {{~/switch~}}
              *

  test:
    runs-on: ubuntu-24.04
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: task install
      - run: npm install -g turbo
      - run: task test
      # - name: Test example
      #   run: |
      #     cd examples/
      #     yarn install --dev
      #     yarn run run || true
      #     file ./tmp/publish-crates-action
