name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (node ${{ matrix.node-version }})
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x
          - 19.x
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn run test

      - name: Test example
        run: |
          cd examples/
          yarn install --dev
          yarn run run || true
          file ./tmp/publish-crates-action
